# Generated by Django 5.1.15 on 2026-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_category', models.CharField(max_length=80)),
                ('quality', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('design', models.CharField(blank=True, max_length=80)),
                ('gsm', models.PositiveIntegerField(blank=True, null=True, verbose_name='GSM')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('m', 'Meter'), ('yd', 'Yard'), ('kg', 'Kg'), ('thaan', 'Thaan')], default='m', max_length=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
