# Generated by Django 5.1.15 on 2026-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='buyer',
            field=models.CharField(default='', max_length=120),
        ),
    ]
