# Generated by Django 5.1.15 on 2026-10-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_buyer'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='design',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='fabric_category',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='width',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fabric'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='stock_added',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
