# Generated by Django 5.1.15 on 2026-10-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='products.fabric')),
            ],
            options={
                'ordering': ['fabric__category__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(choices=[('opening', 'Opening stock'), ('production', 'Production'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], default='adjustment', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.fabric')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
